// LoanGuard-AI — HTTP server.
// Single service: serves the built web app + the governance API + the live SSE event stream.
// Engine modules are mounted here as they are built; this file stays thin.

import 'dotenv/config'
import express from 'express'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, '..')

const app = express()
app.use(express.json({ limit: '15mb' }))

// ---- Seed presence (data is generated by data/generate.js) ----
function readJson(p, fallback) {
  try {
    return JSON.parse(fs.readFileSync(p, 'utf8'))
  } catch {
    return fallback
  }
}
const meta = readJson(path.join(ROOT, 'data', 'meta.json'), { loanCount: 0, taskCount: 0, synthetic: true })

// ---- Health & metadata -------------------------------------------------
app.get('/health', (_req, res) => {
  res.json({
    ok: true,
    service: 'loanguard-ai',
    seeded: meta.loanCount > 0,
    loanCount: meta.loanCount,
    taskCount: meta.taskCount,
    time: new Date().toISOString(),
  })
})

app.get('/api/meta', (_req, res) => {
  res.json(meta)
})

// ---- Engine routes are mounted here as they come online ----
let registerRoutes = null
try {
  const mod = await import('./routes.js')
  registerRoutes = mod.registerRoutes
} catch (e) {
  if (process.env.LOANGUARD_DEBUG) console.warn('[server] routes.js not mounted yet:', e.message)
}
if (registerRoutes) await registerRoutes(app, { ROOT, meta })

// API 404 Handler (Any /api/* route that was not matched above must return JSON 404, not HTML)
app.all('/api/*', (_req, res) => {
  res.status(404).json({ success: false, error: 'API endpoint not found' })
})

// ---- Static web app ----------------------------------------------------
// Prefer the built Vite app; fall back to the placeholder in public/.
const webDist = path.join(ROOT, 'web', 'dist')
const publicDir = path.join(ROOT, 'public')
const staticDir = fs.existsSync(path.join(webDist, 'index.html')) ? webDist : publicDir
app.use(express.static(staticDir))

// SPA fallback (after API routes) — anything not matched serves index.html.
app.get('*', (_req, res) => {
  res.sendFile(path.join(staticDir, 'index.html'))
})

const PORT = process.env.PORT || 8080
app.listen(PORT, () => {
  console.log(`LoanGuard-AI listening on :${PORT} — serving ${staticDir === webDist ? 'web/dist' : 'public (placeholder)'}`)
  console.log(`  seeded: ${meta.loanCount} loans, ${meta.taskCount} tasks`)
})
